# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image for building the TypeScript project
FROM node:22.12-alpine AS builder

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN --mount=type=cache,target=/root/.npm npm install

# Copy the source code
COPY src ./src
COPY tsconfig.json ./

# Build the TypeScript code
RUN npm run build

# Create a lightweight image for production
FROM node:22-alpine

WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/dist /app/dist
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm ci --ignore-scripts --omit=dev

# Expose the port the app runs on
EXPOSE 8080

# Start the MCP server
ENTRYPOINT ["node", "dist/src/index.js"]
